# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  terraform: bulderbank/terraform@2.5.0
# Orchestrate or schedule a set of jobs
#
parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true
  # A parameter per package
  github1:
    type: boolean
    default: false
  github2:
    type: boolean
    default: false


jobs:
  trigger-workflows:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh
workflows:
  version: 2
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows
  # Name the workflow "welcome"
  github1:
    jobs:
      - terraform/install:
          terraform-version: 0.12.2
          terraform-path: github1
      - terraform/lint:
          requires:
            - terraform/install
          terraform-version: 0.12.2
          terraform-path: github1
      - terraform/plan:
          requires:
            - terraform/lint
          terraform-version: 0.12.2
          terraform-path: github1
          filters:
            branches:
              ignore:
                - master
      - terraform/apply:
          requires:
            - terraform/lint
          terraform-version: 0.12.2
          terraform-path: github1
          filters:
            branches:
              only:
                - master
  github2:
    jobs:
      - terraform/install:
          terraform-version: 0.12.2
          terraform-path: github2
      - terraform/lint:
          requires:
            - terraform/install
          terraform-version: 0.12.2
          terraform-path: github2
      - terraform/plan:
          requires:
            - terraform/lint
          terraform-version: 0.12.2
          terraform-path: github2
          filters:
            branches:
              ignore:
                - master
      - terraform/apply:
          requires:
            - terraform/lint
          terraform-version: 0.12.2
          terraform-path: github2
          filters:
            branches:
              only:
                - master
